Импорты

In [ ]:
import pandas as pd

df = pd.read_csv("credit-screening.txt", sep = '\t', na_values='?')
df.head()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Class
0,M,59.0,Village,0.258675,23.717515,18.036528,no,Yes,NaN,Yes,4,1,+
1,f,24.0,Village,0.025412,29.175783,26.840848,No,No,NaN,Yes,4,1,-
2,F,41.0,Сity,0.639816,79.968452,24.138464,Secondary,Yes,NaN,Yes,2,1,-
3,M,46.0,Village,0.322908,36.717792,19.851671,Higher,Yes,NaN,Yes,1,1,+
4,F,41.0,Village,0.911336,75.456025,14.483106,Secondary,No,NaN,Yes,2,1,+

Смотрим таблицу

In [ ]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Attribute1   207 non-null    object
 1   Attribute2   204 non-null    float64
 2   Attribute3   203 non-null    object
 3   Attribute4   205 non-null    float64
 4   Attribute5   203 non-null    float64
 5   Attribute6   206 non-null    float64
 6   Attribute7   205 non-null    object
 7   Attribute8   206 non-null    object
 8   Attribute9   3 non-null      float64
 9   Attribute10  206 non-null    object
 10  Attribute11  207 non-null    int64
 11  Attribute12  207 non-null    int64
 12  Class        207 non-null    object
dtypes: float64(5), int64(2), object(6)
memory usage: 21.2+ KB

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Class
count,207,204.000000,203,205.000000,203.000000,206.000000,205,206,3.0,206,207.000000,207.000000,207
unique,5,NaN,6,NaN,NaN,NaN,6,2,NaN,1,NaN,NaN,3
top,M,NaN,Metropolis,NaN,NaN,NaN,Secondary,Yes,NaN,Yes,NaN,NaN,+
freq,99,NaN,67,NaN,NaN,NaN,69,105,NaN,206,NaN,NaN,77
mean,NaN,45.813725,NaN,0.524778,56.419520,19.739834,NaN,NaN,1.0,NaN,2.560386,0.990338,NaN
std,NaN,14.130448,NaN,0.282239,27.173966,10.667420,NaN,NaN,0.0,NaN,1.713730,0.098056,NaN
min,NaN,20.000000,NaN,0.002511,10.899326,-4.625769,NaN,NaN,1.0,NaN,0.000000,0.000000,NaN
25%,NaN,35.000000,NaN,0.315697,30.922190,11.615835,NaN,NaN,1.0,NaN,1.000000,1.000000,NaN
50%,NaN,45.000000,NaN,0.546552,57.144986,19.364474,NaN,NaN,1.0,NaN,3.000000,1.000000,NaN
75%,NaN,58.000000,NaN,0.759459,81.813651,28.044388,NaN,NaN,1.0,NaN,4.000000,1.000000,NaN
max,NaN,70.000000,NaN,0.996647,99.785321,48.298117,NaN,NaN,1.0,NaN,5.000000,1.000000,NaN

Удаляем полные дубликаты

In [ ]:
df.drop_duplicates()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Class
0,M,59.0,Village,0.258675,23.717515,18.036528,no,Yes,NaN,Yes,4,1,+
1,f,24.0,Village,0.025412,29.175783,26.840848,No,No,NaN,Yes,4,1,-
2,F,41.0,Сity,0.639816,79.968452,24.138464,Secondary,Yes,NaN,Yes,2,1,-
3,M,46.0,Village,0.322908,36.717792,19.851671,Higher,Yes,NaN,Yes,1,1,+
4,F,41.0,Village,0.911336,75.456025,14.483106,Secondary,No,NaN,Yes,2,1,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,M,53.0,city,0.356817,41.015411,5.399424,No,No,NaN,Yes,5,1,-
203,P,67.0,Village,0.586842,95.870387,32.450988,Secondary,Yes,NaN,Yes,2,1,+
204,M,63.0,metropolis,0.489981,56.909474,17.289042,No,No,NaN,Yes,5,1,+-
205,F,51.0,Сity,0.976265,45.468350,26.097208,No,Yes,NaN,Yes,5,1,+
206,M,65.0,metropolis,NaN,NaN,17.289042,NaN,NaN,NaN,NaN,5,1,+-

Проверка на наличие пропусков. Признаки с более чем 50% пропусков - удаляем. Оставшиеся пропуски заполняем средним для числовых и модой для категориальных.

In [ ]:
df.isnull().sum()

threshold = len(df) * 0.5
df = df.dropna(thresh=threshold, axis=1)

for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

<ipython-input-26-f9046c2ea960>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
<ipython-input-26-f9046c2ea960>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col].fillna(df[col].mode()[0], inplace=True)
<ipython-input-26-f9046c2ea960>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
<ipython-input-26-f9046c2ea960>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col].fillna(df[col].mean(), inplace=True)

Приводим категориальные признаки к единому виду

In [ ]:
df['Attribute1'] = df['Attribute1'].str.upper()
df['Attribute1'] = df['Attribute1'].replace({'F': 'F', 'M': 'M', 'P': 'M'})
df['Attribute3'] = df['Attribute3'].str.capitalize()
df['Attribute6'] = df['Attribute6'].astype(str).str.capitalize()

Кодирование признаков.

In [ ]:
from sklearn.preprocessing import LabelEncoder

categoricals = df.select_dtypes(include='object').columns.drop('Class')
for col in categoricals:
    df[col] = LabelEncoder().fit_transform(df[col])

df['Class'] = df['Class'].map({'+': 1, '-': 0, '+-': 2})

Обработка выбросов

In [ ]:
numericals = df.select_dtypes(include=[np.number]).columns.drop('Class')

Q1 = df[numericals].quantile(0.25)
Q3 = df[numericals].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[numericals] < (Q1 - 1.5 * IQR)) | (df[numericals] > (Q3 + 1.5 * IQR))).any(axis=1)]

Z - нормализация

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[numericals] = scaler.fit_transform(df[numericals])

Разделение на обучающую и тестовую выборки

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Class'])
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y, random_state=42)